SeminarManagementSystem/Controllers/AttendeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SeminarManagementSystem.Models;

namespace SeminarManagementSystem.Controllers
{
    public class AttendeeController : Controller
    {
        private readonly database _context;

        public AttendeeController(database context)
        {
            _context = context;
        }

        // GET: Attendee
        public async Task<IActionResult> Index()
        {
            return View(await _context.Attendee.ToListAsync());
        }

        // GET: Attendee/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var attendee = await _context.Attendee
                .FirstOrDefaultAsync(m => m.attendeeID == id);
            if (attendee == null)
            {
                return NotFound();
            }

            return View(attendee);
        }

        // GET: Attendee/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Attendee/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("attendeeID,attendee_name,attendee_DOB")] Attendee attendee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(attendee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(attendee);
        }

        // GET: Attendee/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var attendee = await _context.Attendee.FindAsync(id);
            if (attendee == null)
            {
                return NotFound();
            }
            return View(attendee);
        }

        // POST: Attendee/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("attendeeID,attendee_name,attendee_DOB")] Attendee attendee)
        {
            if (id != attendee.attendeeID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(attendee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AttendeeExists(attendee.attendeeID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(attendee);
        }

        // GET: Attendee/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var attendee = await _context.Attendee
                .FirstOrDefaultAsync(m => m.attendeeID == id);
            if (attendee == null)
            {
                return NotFound();
            }

            return View(attendee);
        }

        // POST: Attendee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var attendee = await _context.Attendee.FindAsync(id);
            _context.Attendee.Remove(attendee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AttendeeExists(int id)
        {
            return _context.Attendee.Any(e => e.attendeeID == id);
        }
    }
}

SeminarManagementSystem/Controllers/OrganiserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SeminarManagementSystem.Models;

namespace SeminarManagementSystem.Controllers
{
    public class OrganiserController : Controller
    {
        private readonly database _context;

        public OrganiserController(database context)
        {
            _context = context;
        }

        // GET: Organiser
        public async Task<IActionResult> Index()
        {
            return View(await _context.Organiser.ToListAsync());
        }

        // GET: Organiser/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organiser = await _context.Organiser
                .FirstOrDefaultAsync(m => m.organiserID == id);
            if (organiser == null)
            {
                return NotFound();
            }

            return View(organiser);
        }

        // GET: Organiser/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Organiser/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("organiserID,organiser_name,organiser_DOB")] Organiser organiser)
        {
            if (ModelState.IsValid)
            {
                _context.Add(organiser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(organiser);
        }

        // GET: Organiser/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organiser = await _context.Organiser.FindAsync(id);
            if (organiser == null)
            {
                return NotFound();
            }
            return View(organiser);
        }

        // POST: Organiser/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("organiserID,organiser_name,organiser_DOB")] Organiser organiser)
        {
            if (id != organiser.organiserID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(organiser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrganiserExists(organiser.organiserID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(organiser);
        }

        // GET: Organiser/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var organiser = await _context.Organiser
                .FirstOrDefaultAsync(m => m.organiserID == id);
            if (organiser == null)
            {
                return NotFound();
            }

            return View(organiser);
        }

        // POST: Organiser/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var organiser = await _context.Organiser.FindAsync(id);
            _context.Organiser.Remove(organiser);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrganiserExists(int id)
        {
            return _context.Organiser.Any(e => e.organiserID == id);
        }
    }
}

SeminarManagementSystem/Controllers/SeminarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SeminarManagementSystem.Models;

namespace SeminarManagementSystem.Controllers
{
    public class SeminarController : Controller
    {
        private readonly database _context;

        public SeminarController(database context)
        {
            _context = context;
        }

        // GET: Seminar
        public async Task<IActionResult> Index()
        {
            var database = _context.Seminar.Include(s => s.organiser).Include(s => s.typeSeminar);
            return View(await database.ToListAsync());
        }

        // GET: Seminar/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seminar = await _context.Seminar
                .Include(s => s.organiser)
                .Include(s => s.typeSeminar)
                .FirstOrDefaultAsync(m => m.seminarID == id);
            if (seminar == null)
            {
                return NotFound();
            }

            return View(seminar);
        }

        // GET: Seminar/Create
        public IActionResult Create()
        {
            ViewData["organiserID"] = new SelectList(_context.Organiser, "organiserID", "organiser_name");
            ViewData["typeSeminarID"] = new SelectList(_context.TypeSeminar, "typeSeminarID", "typeSeminar_Title");
            return View();
        }

        // POST: Seminar/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("seminarID,organiserID,typeSeminarID,seminar_title,seminar_description")] Seminar seminar)
        {
            if (ModelState.IsValid)
            {
                _context.Add(seminar);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["organiserID"] = new SelectList(_context.Organiser, "organiserID", "organiser_name", seminar.organiserID);
            ViewData["typeSeminarID"] = new SelectList(_context.TypeSeminar, "typeSeminarID", "typeSeminar_Title", seminar.typeSeminarID);
            return View(seminar);
        }

        // GET: Seminar/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seminar = await _context.Seminar.FindAsync(id);
            if (seminar == null)
            {
                return NotFound();
            }
            ViewData["organiserID"] = new SelectList(_context.Organiser, "organiserID", "organiser_name", seminar.organiserID);
            ViewData["typeSeminarID"] = new SelectList(_context.TypeSeminar, "typeSeminarID", "typeSeminar_Title", seminar.typeSeminarID);
            return View(seminar);
        }

        // POST: Seminar/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("seminarID,organiserID,typeSeminarID,seminar_title,seminar_description")] Seminar seminar)
        {
            if (id != seminar.seminarID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(seminar);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SeminarExists(seminar.seminarID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["organiserID"] = new SelectList(_context.Organiser, "organiserID", "organiser_name", seminar.organiserID);
            ViewData["typeSeminarID"] = new SelectList(_context.TypeSeminar, "typeSeminarID", "typeSeminar_Title", seminar.typeSeminarID);
            return View(seminar);
        }

        // GET: Seminar/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seminar = await _context.Seminar
                .Include(s => s.organiser)
                .Include(s => s.typeSeminar)
                .FirstOrDefaultAsync(m => m.seminarID == id);
            if (seminar == null)
            {
                return NotFound();
            }

            return View(seminar);
        }

        // POST: Seminar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var seminar = await _context.Seminar.FindAsync(id);
            _context.Seminar.Remove(seminar);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SeminarExists(int id)
        {
            return _context.Seminar.Any(e => e.seminarID == id);
        }
    }
}

SeminarManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> @ViewData["Title"] </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <nav class="navbar navbar-light bg-light">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="@Url.Content("~/Image/image-removebg-preview.png")" width="130" height="50" class="d-inline-block align-top" alt="">
                </a>

                @*<a class="nav-link text-white" id="ttl" asp-area="" asp-controller="Home" asp-action="Index">

                    <div class="row">
                        <img src="@Url.Content("~/Image/icons/home_icon.png")" width="25" height="25">
                        <h5>
                            Home
                        </h5>
                    </div>
                </a>*@


            </nav>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse ml-5" id="navbarNavDropdown">
                <ul class="navbar-nav">

                    <li class="nav-item">
                        <a class="nav-link text-white" id="button-home" asp-area="" asp-controller="Home" asp-action="Index">

                            <div class="box">
                                <img style="vertical-align:middle" src="@Url.Content("~/Image/icons/home_icon.png")" width="25" height="25" >
                                <span style="">Home</span>
                            </div>

                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-dark" id="button-na" asp-area="" asp-controller="Organiser" asp-action="Index">Organiser</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" id="button-na" asp-area="" asp-controller="Attendee" asp-action="Index">Attendee</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" id="button-na" asp-area="" asp-controller="TypeSeminar" asp-action="Index">Seminar Type</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" id="button-na" asp-area="" asp-controller="Seminar" asp-action="Index">Seminar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" id="button-na" asp-area="" asp-controller="EnrolmentSeminar" asp-action="Index">Enrolment</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" id="button-na" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; 2022 KOI Students - All Rights Reserved - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>