SeminarManagementSystem/Models/TypeSeminar.cs
using System.ComponentModel.DataAnnotations;


namespace SeminarManagementSystem.Models
{
    public class TypeSeminar
    {
        [Display(Name = "Seminar Type")]
        public int typeSeminarID { get; set; }

        [Display(Name = "Seminar Type")]
        [Required(ErrorMessage = "Please, enter the seminar title.")]
        [StringLength(40, ErrorMessage = "Please, enter a title with maximum 40 characteres.")]
        public string typeSeminar_Title { get; set; }
    }
}

SeminarManagementSystem/Controllers/TypeSeminarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SeminarManagementSystem.Models;

namespace SeminarManagementSystem.Controllers
{
    public class TypeSeminarController : Controller
    {
        private readonly database _context;

        public TypeSeminarController(database context)
        {
            _context = context;
        }

        // GET: TypeSeminar
        public async Task<IActionResult> Index()
        {
            return View(await _context.TypeSeminar.ToListAsync());
        }

        // GET: TypeSeminar/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var typeSeminar = await _context.TypeSeminar
                .FirstOrDefaultAsync(m => m.typeSeminarID == id);
            if (typeSeminar == null)
            {
                return NotFound();
            }

            return View(typeSeminar);
        }

        // GET: TypeSeminar/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TypeSeminar/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("typeSeminarID,typeSeminar_Title")] TypeSeminar typeSeminar)
        {
            if (ModelState.IsValid)
            {
                _context.Add(typeSeminar);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(typeSeminar);
        }

        // GET: TypeSeminar/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var typeSeminar = await _context.TypeSeminar.FindAsync(id);
            if (typeSeminar == null)
            {
                return NotFound();
            }
            return View(typeSeminar);
        }

        // POST: TypeSeminar/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("typeSeminarID,typeSeminar_Title")] TypeSeminar typeSeminar)
        {
            if (id != typeSeminar.typeSeminarID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(typeSeminar);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TypeSeminarExists(typeSeminar.typeSeminarID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(typeSeminar);
        }

        // GET: TypeSeminar/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var typeSeminar = await _context.TypeSeminar
                .FirstOrDefaultAsync(m => m.typeSeminarID == id);
            if (typeSeminar == null)
            {
                return NotFound();
            }

            return View(typeSeminar);
        }

        // POST: TypeSeminar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var typeSeminar = await _context.TypeSeminar.FindAsync(id);
            _context.TypeSeminar.Remove(typeSeminar);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TypeSeminarExists(int id)
        {
            return _context.TypeSeminar.Any(e => e.typeSeminarID == id);
        }
    }
}

SeminarManagementSystem/Views/TypeSeminar/Create.cshtml
@model SeminarManagementSystem.Models.TypeSeminar

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Seminar Type</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="typeSeminar_Title" class="control-label"></label>
                <input asp-for="typeSeminar_Title" class="form-control" />
                <span asp-validation-for="typeSeminar_Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SeminarManagementSystem/Views/TypeSeminar/Delete.cshtml
@model SeminarManagementSystem.Models.TypeSeminar

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TypeSeminar</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.typeSeminar_Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.typeSeminar_Title)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="typeSeminarID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SeminarManagementSystem/Views/TypeSeminar/Details.cshtml
@model SeminarManagementSystem.Models.TypeSeminar

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TypeSeminar</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.typeSeminar_Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.typeSeminar_Title)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.typeSeminarID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SeminarManagementSystem/Views/TypeSeminar/Edit.cshtml
@model SeminarManagementSystem.Models.TypeSeminar

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TypeSeminar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="typeSeminarID" />
            <div class="form-group">
                <label asp-for="typeSeminar_Title" class="control-label"></label>
                <input asp-for="typeSeminar_Title" class="form-control" />
                <span asp-validation-for="typeSeminar_Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SeminarManagementSystem/Views/TypeSeminar/Index.cshtml
@model IEnumerable<SeminarManagementSystem.Models.TypeSeminar>

@{
    ViewData["Title"] = "Seminar Type";
}
<div class="container">
    <div class="card">
        <div class="card-body">

            <div class="row card-header align-card">
                <img src="@Url.Content("~/Image/icons/seminar_type_icon.png")" width="60" height="60">
                <h1 class="header-title mt-2">Seminar Type</h1>
            </div>

            <table id="grid" class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.typeSeminar_Title)
                        </th>

                        <th scope="col">Options</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.typeSeminar_Title)
                            </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.typeSeminarID">Edit</a> |
                                <a asp-action="Details" asp-route-id="@item.typeSeminarID">Details</a> |
                                <a asp-action="Delete" asp-route-id="@item.typeSeminarID">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="container d-flex flex-column col-md-8" id="create-button">

                <div class="row flex-column">
                    <button type="button"
                            class="col-4 align-self-end btn btn-primary btn-lg"
                            value="Create"
                            onclick="location.href='@Url.Action("Create", "TypeSeminar")'">
                        <img src="@Url.Content("~/Image/new_icon.png")" width="25" height="25">
                        New Type
                    </button>
                </div>

            </div>
        </div>
    </div>
</div>