SeminarManagementSystem/Models/EnrolmentSeminar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace SeminarManagementSystem.Models
{
    public class EnrolmentSeminar
    {

        [Display(Name = "Enrolment")]
        public int enrolmentSeminarID { get; set; }

        [Display(Name = "Seminar")]
        [Required(ErrorMessage = "Please, select a valid seminar.")]
        public int seminarID { get; set; }

        [Display(Name = "Attendee")]
        [Required(ErrorMessage = "Please, select a valid attendee.")]
        public int attendeeID { get; set; }

        [Display(Name = "Seminar")]
        public Seminar seminar {  get;set;}

        [Display(Name = "Attendee")]
        public Attendee attendee { get; set; }

    }
}

SeminarManagementSystem/Controllers/EnrolmentSeminarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SeminarManagementSystem.Models;

namespace SeminarManagementSystem.Controllers
{
    public class EnrolmentSeminarController : Controller
    {
        private readonly database _context;

        public EnrolmentSeminarController(database context)
        {
            _context = context;
        }

        // GET: EnrolmentSeminar
        public async Task<IActionResult> Index()
        {
            var database = _context.EnrolmentSeminar.Include(e => e.attendee).Include(e => e.seminar);
            return View(await database.ToListAsync());
        }

        // GET: EnrolmentSeminar/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrolmentSeminar = await _context.EnrolmentSeminar
                .Include(e => e.attendee)
                .Include(e => e.seminar)
                .FirstOrDefaultAsync(m => m.enrolmentSeminarID == id);
            if (enrolmentSeminar == null)
            {
                return NotFound();
            }

            return View(enrolmentSeminar);
        }

        // GET: EnrolmentSeminar/Create
        public IActionResult Create()
        {
            ViewData["attendeeID"] = new SelectList(_context.Attendee, "attendeeID", "attendee_name");
            ViewData["seminarID"] = new SelectList(_context.Seminar, "seminarID", "seminar_title");
            return View();
        }

        // POST: EnrolmentSeminar/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("enrolmentSeminarID,seminarID,attendeeID")] EnrolmentSeminar enrolmentSeminar)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enrolmentSeminar);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["attendeeID"] = new SelectList(_context.Attendee, "attendeeID", "attendee_name", enrolmentSeminar.attendeeID);
            ViewData["seminarID"] = new SelectList(_context.Seminar, "seminarID", "seminar_title", enrolmentSeminar.seminarID);
            return View(enrolmentSeminar);
        }

        // GET: EnrolmentSeminar/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrolmentSeminar = await _context.EnrolmentSeminar.FindAsync(id);
            if (enrolmentSeminar == null)
            {
                return NotFound();
            }
            ViewData["attendeeID"] = new SelectList(_context.Attendee, "attendeeID", "attendee_name", enrolmentSeminar.attendeeID);
            ViewData["seminarID"] = new SelectList(_context.Seminar, "seminarID", "seminar_title", enrolmentSeminar.seminarID);
            return View(enrolmentSeminar);
        }

        // POST: EnrolmentSeminar/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("enrolmentSeminarID,seminarID,attendeeID")] EnrolmentSeminar enrolmentSeminar)
        {
            if (id != enrolmentSeminar.enrolmentSeminarID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(enrolmentSeminar);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnrolmentSeminarExists(enrolmentSeminar.enrolmentSeminarID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["attendeeID"] = new SelectList(_context.Attendee, "attendeeID", "attendee_name", enrolmentSeminar.attendeeID);
            ViewData["seminarID"] = new SelectList(_context.Seminar, "seminarID", "seminar_title", enrolmentSeminar.seminarID);
            return View(enrolmentSeminar);
        }

        // GET: EnrolmentSeminar/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrolmentSeminar = await _context.EnrolmentSeminar
                .Include(e => e.attendee)
                .Include(e => e.seminar)
                .FirstOrDefaultAsync(m => m.enrolmentSeminarID == id);
            if (enrolmentSeminar == null)
            {
                return NotFound();
            }

            return View(enrolmentSeminar);
        }

        // POST: EnrolmentSeminar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var enrolmentSeminar = await _context.EnrolmentSeminar.FindAsync(id);
            _context.EnrolmentSeminar.Remove(enrolmentSeminar);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EnrolmentSeminarExists(int id)
        {
            return _context.EnrolmentSeminar.Any(e => e.enrolmentSeminarID == id);
        }
    }
}

SeminarManagementSystem/Views/EnrolmentSeminar/Create.cshtml
@model SeminarManagementSystem.Models.EnrolmentSeminar

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Enrolment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="seminarID" class="control-label"></label>
                <select asp-for="seminarID" class ="form-control" asp-items="ViewBag.seminarID"></select>
            </div>
            <div class="form-group">
                <label asp-for="attendeeID" class="control-label"></label>
                <select asp-for="attendeeID" class ="form-control" asp-items="ViewBag.attendeeID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SeminarManagementSystem/Views/EnrolmentSeminar/Delete.cshtml
@model SeminarManagementSystem.Models.EnrolmentSeminar

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EnrolmentSeminar</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.seminar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.seminar.seminar_description)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.attendee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.attendee.attendee_name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="enrolmentSeminarID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SeminarManagementSystem/Views/EnrolmentSeminar/Details.cshtml
@model SeminarManagementSystem.Models.EnrolmentSeminar

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>EnrolmentSeminar</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.seminar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.seminar.seminar_description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.attendee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.attendee.attendee_name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.enrolmentSeminarID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SeminarManagementSystem/Views/EnrolmentSeminar/Edit.cshtml
@model SeminarManagementSystem.Models.EnrolmentSeminar

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>EnrolmentSeminar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="enrolmentSeminarID" />
            <div class="form-group">
                <label asp-for="seminarID" class="control-label"></label>
                <select asp-for="seminarID" class="form-control" asp-items="ViewBag.seminarID"></select>
                <span asp-validation-for="seminarID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="attendeeID" class="control-label"></label>
                <select asp-for="attendeeID" class="form-control" asp-items="ViewBag.attendeeID"></select>
                <span asp-validation-for="attendeeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SeminarManagementSystem/Views/EnrolmentSeminar/Index.cshtml
@model IEnumerable<SeminarManagementSystem.Models.EnrolmentSeminar>

@{
    ViewData["Title"] = "Enrolment";
 }
<div class="container">
    <div class="card">
        <div class="card-body">

            <div class="row card-header align-card">
                <img src="@Url.Content("~/Image/icons/enrolment_icon.png")" width="60" height="60">
                <h1 class="header-title mt-2">Enrolment</h1>
            </div>

            <table id="grid" class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.seminar)
                        </th>

                        @*<th scope="col">
                            @Html.DisplayNameFor(model => model.seminar.organiser)
                        </th>*@

                        <th scope="col">
                            @Html.DisplayNameFor(model => model.attendee)
                        </th>
                        <th scope="col">Options</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.seminar.seminar_title)
                        </td>
                        @*<td>
                            @Html.DisplayFor(modelItem => item.seminar.organiserID)
                        </td>*@
                        <td>
                            @Html.DisplayFor(modelItem => item.attendee.attendee_name)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.enrolmentSeminarID">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.enrolmentSeminarID">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.enrolmentSeminarID">Delete</a>
                        </td>
                    </tr>}
                </tbody>
            </table>
            <div class="container d-flex flex-column col-md-8" id="create-button">

                <div class="row flex-column">
                    <button type="button"
                            class="col-4 align-self-end btn btn-primary btn-lg"
                            value="Create"
                            onclick="location.href='@Url.Action("Create", "EnrolmentSeminar")'">
                        <img src="@Url.Content("~/Image/new_icon.png")" width="25" height="25">
                        New Enrolment
                    </button>
                </div>

            </div>
        </div>
    </div>
</div>